openapi: 3.0.2

info:
  title: Smarbar Backoffice AP
  description: Smarbar Backoffice AP
  version: 1.0.0
paths:
  /categories:
    get:
      summary: get list of categories
      description:  get  list of **categories**
      operationId: getCategories
      tags:
        - Categories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/apiCategory"
    post:
      summary: create a new category
      description: create a new **category**
      operationId: createCategory
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiCategory"
      responses:
        201:
          description: Success
          $ref: "#/components/responses/201"
  /categories/{categoryId}:
    parameters:
      - name: categoryId
        schema:
           $ref: "#/components/schemas/id"
        in: path
        required: true
    put:
      summary: update a category by id
      description: update a **category** by its id
      operationId: updateCategoryById
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiCategory"
      responses:
        200:
          description: Entity successfully updated
    delete:
      summary: delete a category by id
      description: delete a **category** by its id
      operationId: deleteCategoryById
      tags:
        - Categories
      responses:
        200:
          description: Entity successfully deleted
    get:
      summary: get a category by id
      description: get a **category** by its id
      operationId: getCategoryById
      tags:
        - Categories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiCategory"
  /articles:
    get:
      summary: get list of articles
      description:  get  list of **articles**
      operationId: getArticles
      tags:
        - Articles
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/apiArticle"
    post:
      summary: create a new article
      description: create a new **article**
      operationId: createArticle
      tags:
        - Articles
      parameters:
        - name: x-category-id
          in: header
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiArticle"
      responses:
        201:
          $ref: "#/components/responses/201"
  /articles/{articleId}:
    parameters:
      - name: articleId
        schema:
          $ref: "#/components/schemas/id"
        in: path
        required: true
    put:
      summary: update a article by id
      description: update a **article** by its id
      operationId: updateArticleById
      tags:
        - Articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiArticle"
      responses:
        200:
          description: Entity successfully updated
    delete:
      summary: delete a article by id
      description: delete a **article** by its id
      operationId: deleteArticleById
      tags:
        - Articles
      responses:
        200:
          description: Entity successfully deleted
    get:
      summary: get a article by id
      description: get a **article** by its id
      operationId: getArticleById
      tags:
        - Articles
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiArticle"
  /tables:
    get:
      operationId: getTables
      tags:
        - Tables
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/apiTable"
    post:
      operationId: createTable
      tags:
        - Tables
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiTable"
      responses:
        201:
          $ref: "#/components/responses/201"
  /tables/{tableId}:
    parameters:
      - name: tableId
        schema:
           $ref: "#/components/schemas/id"
        in: path
        required: true
    put:
      operationId: updateTableById
      tags:
        - Tables
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiTable"
      responses:
        200:
          description: Entity successfully updated
    delete:
      operationId: deleteTableById
      tags:
        - Tables
      responses:
        200:
          description: Entity successfully deleted
    get:
      operationId: getTableById
      tags:
        - Tables
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiTable"
components:
  schemas:
    apiCategory:
      type: object
      required:
        - name
        - description
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    apiArticle:
      type: object
      required:
        - name
        - price
        - picture
        - description
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
        description:
          type: string
        picture:
          type: string
    apiTable:
      type: object
      required:
        - name
        - seatCount
        - active
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        seatCount:
          type: integer
        active:
          type: boolean
    id:
      type: integer
      format: int64
  responses:
    201:
      description: Entity successfully created
      headers:
        Location:
          description: Entity successfully created
          schema:
            type: string